# Generated by Django 5.2 on 2025-09-30 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Administrador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
            ],
            options={
                'db_table': 'Grupo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(db_column='Dia', max_length=15)),
                ('horario_inicio', models.TimeField(db_column='HorarioInicio')),
                ('hora_fin', models.TimeField(db_column='HoraFin')),
            ],
            options={
                'db_table': 'Horario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('email', models.EmailField(db_column='Email', max_length=100, unique=True)),
                ('rol', models.CharField(db_column='Rol', max_length=50)),
            ],
            options={
                'db_table': 'Usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('codigo', models.CharField(db_column='Codigo', max_length=20)),
            ],
            options={
                'db_table': 'Materia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MateriaGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'MateriaGrupo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MateriaHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'MateriaHorario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PreferenciaMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferencia_nivel', models.IntegerField(db_column='PreferenciaNivel')),
            ],
            options={
                'db_table': 'PreferenciaMateria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('especialidad', models.CharField(db_column='Especialidad', max_length=100)),
            ],
            options={
                'db_table': 'Profesor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('usuario_fk', models.OneToOneField(db_column='UsuarioId', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='my_proyecto.usuario')),
                ('usuario', models.CharField(db_column='Usuario', max_length=100, unique=True)),
                ('contrasena', models.CharField(db_column='Contrasena', max_length=100)),
            ],
            options={
                'db_table': 'Login',
                'managed': False,
            },
        ),
    ]
